In [ ]:
import numpy as np
import torch

In [ ]:
#import dataset
inputs=np.array([[73,67,43],
                 [91,88,64],
                 [87,134,58],
                 [102,43,37],
                 [69,96,70]],dtype="float32")
targets=np.array([[56],
                  [81],
                  [119],
                  [22],
                  [103]],dtype="float32")

In [ ]:
#convert to tensor
input_t=torch.from_numpy(inputs)
targets_t=torch.from_numpy(targets)

In [ ]:
#value of theta1,2,3
weight=torch.randn(1,3,requires_grad = True)
print(weight)

tensor([[0.6369, 0.6598, 0.2101]], requires_grad=True)


In [ ]:
#bias value(theta 0)
bias=torch.randn(1,1,requires_grad = True)

In [ ]:
#Prediction
def model(X):
  return X@weight.t() + bias
  # model= input_t@weight.t() + bias
  print(model)

In [ ]:
#Loss function
model_pred=model(input_t)
m=5
MSE=0
for i in range (0,m):
  MSE=MSE+(model_pred[i]-targets_t[i])**2
MSE=MSE*(1/2*m)
print(MSE)


tensor([31424.3652], grad_fn=<MulBackward0>)


In [ ]:
MSE.backward(retain_graph=True)
# MSE.backward()
# weight.grad
# print(gradient)

In [ ]:
bias.grad

tensor([[1154.0006]])

In [ ]:
def gradient_decent(x,y):
  w_curr=b_curr=0 #set current bias and weigth to 0
  iterations=100
  n=len(x)
  learning_rate=0.0001
  for i in range (iterations):
    y_pred=w_curr*x + b_curr
    cost=(1/n)*sum([val**2 for val in (y_pred-y)])
    wd=-(2/n)*sum(x*(y_pred-y)) #derivative of with respect to weight
    bd=-(2/n)*sum(y_pred-y) 
    w_curr=w_curr-learning_rate*wd
    b_curr=b_curr-learning_rate*bd
    print("m: ",w_curr,"b: ",b_curr,"cost: ", cost )



In [ ]:

gradient_decent(input_t,targets_t)

m:  tensor([-1.2465, -1.5064, -0.9007]) b:  tensor([-0.0152, -0.0152, -0.0152]) cost:  tensor([6990.2002, 6990.2002, 6990.2002])
m:  tensor([-4.3054, -5.4989, -2.3629]) b:  tensor([-0.0515, -0.0563, -0.0403]) cost:  tensor([33828.2070, 48411.9219, 17634.6582])
m:  tensor([-11.8119, -16.0802,  -4.7364]) b:  tensor([-0.1395, -0.1657, -0.0812]) cost:  tensor([195443.9219, 339370.0312,  45684.2383])
m:  tensor([-30.2324, -44.1244,  -8.5893]) b:  tensor([-0.3541, -0.4562, -0.1480]) cost:  tensor([1168677.6250, 2383144.0000,  119598.6797])
m:  tensor([ -75.4357, -118.4510,  -14.8438]) b:  tensor([-0.8797, -1.2270, -0.2567]) cost:  tensor([ 7029393.0000, 16739205.0000,   314373.1875])
m:  tensor([-186.3624, -315.4414,  -24.9968]) b:  tensor([-2.1685, -3.2703, -0.4335]) cost:  tensor([4.2322e+07, 1.1758e+08, 8.2763e+05])
m:  tensor([-458.5716, -837.5326,  -41.4782]) b:  tensor([-5.3300, -8.6866, -0.7208]) cost:  tensor([2.5485e+08, 8.2592e+08, 2.1801e+06])
m:  tensor([-1126.5612, -2221.2505,  

### **Linear regression using PyTorch built-ins**

**Define DataLoader**

In [1]:
import numpy as np
import torch

In [2]:
# Targets (apples, oranges)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [3]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [4]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [6]:
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [7]:
from torch.utils.data import DataLoader

In [8]:
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [9]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 73.,  67.,  43.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 87., 134.,  58.],
        [ 91.,  88.,  64.]])
tensor([[ 56.,  70.],
        [ 22.,  37.],
        [103., 119.],
        [119., 133.],
        [ 81., 101.]])


**nn.Linear**

In [10]:
import torch.nn as nn

In [11]:
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.0494,  0.0411,  0.1555],
        [-0.3859,  0.1490,  0.4638]], requires_grad=True)
Parameter containing:
tensor([0.1057, 0.2067], requires_grad=True)


In [12]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.0494,  0.0411,  0.1555],
         [-0.3859,  0.1490,  0.4638]], requires_grad=True),
 Parameter containing:
 tensor([0.1057, 0.2067], requires_grad=True)]

In [13]:
preds = model(inputs)
preds

tensor([[  5.9395,   1.9549],
        [  9.1790,   7.8751],
        [ 10.3350,  13.4890],
        [  2.5861, -15.5954],
        [ 11.5285,  20.3403]], grad_fn=<AddmmBackward0>)

**loss functions**

In [14]:
import torch.nn.functional as F

In [15]:
loss_fn = F.mse_loss

In [16]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(6830.1626, grad_fn=<MseLossBackward0>)


**Optimizer**

In [17]:
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

**Train for multiple epochs**

In [18]:
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [19]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss: 432.7986
Epoch [20/100], Loss: 219.8157
Epoch [30/100], Loss: 190.9613
Epoch [40/100], Loss: 168.6076
Epoch [50/100], Loss: 148.9728
Epoch [60/100], Loss: 131.6743
Epoch [70/100], Loss: 116.4325
Epoch [80/100], Loss: 103.0019
Epoch [90/100], Loss: 91.1668
Epoch [100/100], Loss: 80.7366


In [20]:
prediction = model(inputs)
prediction

tensor([[ 60.8591,  72.1048],
        [ 83.2043, 100.9534],
        [110.4863, 129.4281],
        [ 42.2960,  47.1540],
        [ 91.2968, 113.7555]], grad_fn=<AddmmBackward0>)

In [21]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [22]:
model(torch.tensor([[75, 63, 44.]]))

tensor([[58.6670, 69.8030]], grad_fn=<AddmmBackward0>)