**1_NB_Classifier**

In [ ]:
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB, MultinomialNB
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split #for spliting training testing data
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

In [ ]:
#importing data and stored as array
dataset1=pd.read_csv("/content/Dataset1.csv")

Outlook=np.array(dataset1['Outlook'])
Temp=np.array(dataset1['Temp'])
Humidity=np.array(dataset1['Humidity'])
Wind=np.array(dataset1['Wind'])
Play=np.array(dataset1['Play'])
print(Humidity)

['Normal' 'High' 'Normal' 'Normal' 'Normal' 'Low' 'Normal' 'Normal' 'Low'
 'High' 'High' 'Low' 'Normal' 'Normal']


In [ ]:
#Label Encoding
le=preprocessing.LabelEncoder()

#label into numbers
outlook_encoded=le.fit_transform(Outlook)
temp_encoded=le.fit_transform(Temp)
Play_encoded=le.fit_transform(Play)
print(Play_encoded)

[0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [ ]:
#Combinig weather and temp into single listof tuples
features=tuple(zip(outlook_encoded,temp_encoded))
print(features)

((1, 1), (1, 1), (0, 1), (2, 2), (2, 0), (2, 0), (0, 0), (1, 2), (1, 0), (2, 2), (1, 2), (0, 2), (0, 1), (2, 2))


In [ ]:
#Create a Classifier
model=MultinomialNB()
# Train the model using the training sets
model.fit(features,Play_encoded)

MultinomialNB()

In [ ]:
#Predict output
predicted=model.predict([[0,1]]) #overcast, hot
print(predicted)

[1]


In [ ]:
#Predict output
predicted=model.predict([[2,2]]) #sunny, mild
print(predicted)

[1]


**2_Gaussian_NB**

In [ ]:
#load iris dataset
iris = datasets.load_iris()
#getting first 50 rows of iris
newdata = iris.data[50:,:]
newtarget = iris.target[50:]
print("newdata",newdata)
print("newtarget",newtarget)

newdata [[7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [4.9 2.4 3.3 1. ]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.9 1.4]
 [5.  2.  3.5 1. ]
 [5.9 3.  4.2 1.5]
 [6.  2.2 4.  1. ]
 [6.1 2.9 4.7 1.4]
 [5.6 2.9 3.6 1.3]
 [6.7 3.1 4.4 1.4]
 [5.6 3.  4.5 1.5]
 [5.8 2.7 4.1 1. ]
 [6.2 2.2 4.5 1.5]
 [5.6 2.5 3.9 1.1]
 [5.9 3.2 4.8 1.8]
 [6.1 2.8 4.  1.3]
 [6.3 2.5 4.9 1.5]
 [6.1 2.8 4.7 1.2]
 [6.4 2.9 4.3 1.3]
 [6.6 3.  4.4 1.4]
 [6.8 2.8 4.8 1.4]
 [6.7 3.  5.  1.7]
 [6.  2.9 4.5 1.5]
 [5.7 2.6 3.5 1. ]
 [5.5 2.4 3.8 1.1]
 [5.5 2.4 3.7 1. ]
 [5.8 2.7 3.9 1.2]
 [6.  2.7 5.1 1.6]
 [5.4 3.  4.5 1.5]
 [6.  3.4 4.5 1.6]
 [6.7 3.1 4.7 1.5]
 [6.3 2.3 4.4 1.3]
 [5.6 3.  4.1 1.3]
 [5.5 2.5 4.  1.3]
 [5.5 2.6 4.4 1.2]
 [6.1 3.  4.6 1.4]
 [5.8 2.6 4.  1.2]
 [5.  2.3 3.3 1. ]
 [5.6 2.7 4.2 1.3]
 [5.7 3.  4.2 1.2]
 [5.7 2.9 4.2 1.3]
 [6.2 2.9 4.3 1.3]
 [5.1 2.5 3.  1.1]
 [5.7 2.8 4.1 1.3]
 [6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]
 [7.

In [ ]:
#split data set into train and test sets
data_train, data_test, target_train, target_test = train_test_split(newdata,
newtarget, test_size = 0.20, random_state = 5)

In [ ]:
gnb=GaussianNB()
#Train the model
gnb.fit(data_train,target_train)

GaussianNB()

In [ ]:
#Predict the output(Testing)
target_predicted=gnb.predict(data_test)
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(target_test, target_predicted))

Accuracy: 0.9


In [ ]:
confusion_matrix(target_test, target_predicted)

array([[12,  1],
       [ 1,  6]])

In [ ]:
precision = precision_score(target_test, target_predicted)
recall = recall_score(target_test, target_predicted)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: 0.9230769230769231
recall: 0.9230769230769231


**3_Task1**

In [ ]:
#Task 1: Try the algo on Dataset1 - OneHotEncoding of features: and Train test Division 70%-30%
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
#Use One Hot Encoder from scikit learn
onehotencoder=OneHotEncoder()
newdata1=onehotencoder.fit_transform(features).toarray()
print(newdata1)

[[0. 1. 0. 0. 1. 0.]
 [0. 1. 0. 0. 1. 0.]
 [1. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1.]
 [0. 0. 1. 1. 0. 0.]
 [0. 0. 1. 1. 0. 0.]
 [1. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 1.]
 [0. 1. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 1.]
 [0. 1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1.]]


In [ ]:
#split data set into train and test sets
data_train, data_test, target_train, target_test = train_test_split(newdata1,Play_encoded, test_size = 0.30, random_state = 5)

#Train the model
gnb.fit(data_train,target_train)

GaussianNB()

In [ ]:
#Predict the output(Testing)
target_predicted=gnb.predict(data_test)
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(target_test, target_predicted))

Accuracy: 0.6


In [ ]:
confusion_matrix(target_test, target_predicted)

array([[2, 1],
       [1, 1]])

In [ ]:
precision = precision_score(target_test, target_predicted)
recall = recall_score(target_test, target_predicted)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: 0.5
recall: 0.5


**Task_2**

In [ ]:
##Task 2: Apply algorithm on digits dataset - LabelEncoding of features: and Train test Division 80%-20%
#Label Encoding
le=preprocessing.LabelEncoder()

#label into numbers
outlook_encoded=le.fit_transform(Outlook)
temp_encoded=le.fit_transform(Temp)
Play_encoded=le.fit_transform(Play)

In [ ]:
#Combinig weather and temp into single listof tuples
features=tuple(zip(outlook_encoded,temp_encoded))

data_train, data_test, target_train, target_test = train_test_split(features,Play_encoded, test_size = 0.20, random_state = 5)


In [ ]:
#Predict the output(Testing)
target_predicted=gnb.predict(data_test)
# Model Accuracy, how often is the classifier correct?
# print("Accuracy:",metrics.accuracy_score(target_test, target_predicted))

ValueError: ignored